systemLog:
  destination: file
  path: /var/log/mongodb/mongod.log
  logAppend: true
  verbosity: 0
  component:
    storage:
      verbosity: 0
    command:
      verbosity: 0
    network:
      verbosity: 0